# Copyright 2018 Steffen Butzer
#
# If licensing should apply to this file, 
# this is free and unencumbered software released into the public domain.
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this file, for any purpose, commercial or non-commercial, and by any
# means.
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
# For more information, please refer to <http://unlicense.org>

environment:
  PROJ_NAME: sqlite3shell
  PROJ_PATH: src/github.com/cznic

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GOPATH: C:\gopath
      GOARCH: 386
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GOPATH: C:\gopath
      GOARCH: amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu
      GOPATH: /home/appveyor/gopath
      GOARCH: 386
    - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu
      GOPATH: /home/appveyor/gopath
      GOARCH: amd64

stack: go 1.10

install:
  - cd ..
  - ps: $env:PROJ_PATH = $env:GOPATH + "/" + $env:PROJ_PATH
  - ps: $env:PROJ_FULL_PATH = $env:PROJ_PATH + "/" + $env:PROJ_NAME 
  - ps: New-Item $env:PROJ_PATH -ItemType Directory 
  - ps: Move-Item $env:APPVEYOR_BUILD_FOLDER $env:PROJ_FULL_PATH 
  - ps: Set-Location -Path $env:PROJ_FULL_PATH 
  - go get -d ./...

build: off

test_script:
  - go test -timeout 999m -v
